### ISSUE TITLE
[RFC #0093] - Remove Shell Processes

### ISSUE THREAD

**Issue by mboldt** [buildpack/rfcs#222]
[RFC #0093](https://github.com/buildpacks/rfcs/blob/main/text/0093-remove-shell-processes.md) - Remove Shell Processes

Spec:
- [x] https://github.com/buildpacks/spec/issues/245
- [x] Released in Platform API version `0.10`
- [x] https://github.com/buildpacks/spec/issues/244
- [x] Released in Buildpack API version `0.9`

Lifecycle:
- [x] https://github.com/buildpacks/lifecycle/issues/693
- [x] https://github.com/buildpacks/lifecycle/issues/870
- [x] Released in lifecycle version `0.15.0`

Libcnb:
- [x] https://github.com/buildpacks/libcnb/issues/70
- [x] Released in libcnb version `TBD`

Pack:
- [x] https://github.com/buildpacks/pack/issues/1260
- [x] Released in pack version `0.28`

Documentation:
- [x] https://github.com/buildpacks/docs/issues/391

Profile Buildpack:
- [x] https://github.com/buildpacks/profile (initial release)
- [x] Released in Profile Buildpack version `0.1.0`

Depends on System Buildpacks RFC implementation (for Profile Buildpack):
- [ ] https://github.com/buildpacks/rfcs/issues/209
- [ ] Released in lifecycle version `TBD`
