### ISSUE TITLE
[RFC #0125] - Export App Image and Cache Image in Parallel

### ISSUE THREAD

**Issue by natalieparellano** [buildpack/rfcs#303]
[RFC #0125](https://github.com/buildpacks/rfcs/blob/main/text/0125-lifecycle-parallel-export.md) - Export App Image and Cache Image in Parallel

Spec:
- [ ] https://github.com/buildpacks/spec/issues/<INSERT ISSUE NUMBER>
- [ ] Released in <INSERT API - e.g., platform> API version `<placeholder>`

Lifecycle:
- [ ] https://github.com/buildpacks/lifecycle/issues/<INSERT ISSUE NUMBER>
- [ ] Released in lifecycle version `<placeholder>`

Pack:
- [ ] https://github.com/buildpacks/pack/issues/<INSERT ISSUE NUMBER>
- [ ] Released in pack version `<placeholder>`

Documentation:
- [ ] https://github.com/buildpacks/docs/issues/<INSERT ISSUE NUMBER>

**Maintainers**: when closing this issue as completed, submit a PR to update the `Status` of the RFC to `Implemented`.
