### ISSUE TITLE
[RFC #0131] - Build Observability

### ISSUE THREAD

**Issue by joshwlewis** [buildpack/rfcs#320]
RFC 0131 - Build Observability:
- [Discussion Pull Request](https://github.com/buildpacks/rfcs/pull/299)
- [Text](https://github.com/buildpacks/rfcs/blob/main/text/0131-build-observability.md)

Spec:
- [ ] https://github.com/buildpacks/spec/issues/412
- [ ] Released in <INSERT API - e.g., platform> API version `<placeholder>`

Lifecycle:
- [ ] https://github.com/buildpacks/lifecycle/issues/1429
- [ ] Released in lifecycle version `<placeholder>`

Libcnb:
- [ ] https://github.com/buildpacks/libcnb/issues/<INSERT ISSUE NUMBER>
- [ ] Released in libcnb version `<placeholder>`

Pack:
- [ ] https://github.com/buildpacks/pack/issues/<INSERT ISSUE NUMBER>
- [ ] Released in pack version `<placeholder>`

Documentation:
- [ ] https://github.com/buildpacks/docs/issues/<INSERT ISSUE NUMBER>

Other?:
- [ ] <INSERT ISSUE URL>
- [ ] Released in <INSERT COMPONENT> version `<placeholder>`

**Maintainers**: when closing this issue as completed, submit a PR to update the `Status` of the RFC to `Implemented`.
